// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  buttonExpand: string;
  buttonsWrapper: string;
  cardWrapper: string;
  root: string;
  searchField: string;
  searchFieldWrapper: string;
  title: string;
}
export const cssExports: CssExports;
export default cssExports;
